### ISSUE TITLE
API was down?

### ISSUE THREAD

**Issue by vanthang91** [sandipbgt/theastrologer-api#3]
Hi sandipbgt, could you check your horoscope-api, it was not working from last week.
Thanks

**Comment by sandipbgt** [comment]
Hello @vanthang91 , The api was hosted on Heroku free plan and due to the heavy usage of the api, it crossed the usage limit of the free plan and was ultimately shutdown. So I have to move the api to new url [http://sandipbgt.com/theastrologer/api/](http://sandipbgt.com/theastrologer/api/)

Everything works same as before except the domain name has been changed from  [https://theastrologer-api.herokuapp.com/api](https://theastrologer-api.herokuapp.com/api)
to [http://sandipbgt.com/theastrologer/api/](http://sandipbgt.com/theastrologer/api/)

So, to get Aquarius today's horoscope, you have to call this url
[http://sandipbgt.com/theastrologer/api/horoscope/aquarius/today](http://sandipbgt.com/theastrologer/api/horoscope/aquarius/today)

Also, now you can also get list of all sunsigns
http://sandipbgt.com/theastrologer/api/sunsigns

**Comment by vanthang91** [comment]
It's ok now, thank you so much @sandipbgt

**Comment by nirav10** [comment]
Is there any API to get details weekly,monthly,yearly

https://new.theastrologer.com/weekly-horoscope/
https://new.theastrologer.com/monthly-horoscope/
https://new.theastrologer.com/2018-horoscope/
